name: Linux build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: sudo apt install libssl-dev

      - name: Build git-crypt
        run: make LDFLAGS="-lcrypto"

      - name: Create Release
        if: contains(github.ref, 'release')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Linux ${{ github.ref }}
          draft: true
          prerelease: false

      - name: zip artifacts
        run: |
          zip --junk-paths -r git-crypt-linux.zip git-crypt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: git-crypt-linux.zip

      - name: Upload Release Asset
        if: contains(github.ref, 'release')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./git-crypt-linux.zip
          asset_name: git-crypt-linux.zip
          asset_content_type: application/zip
