name: Windows build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        install: git msys2-devel base-devel libssl-dev
        with:
          msystem: MINGW64

      - name: Build git-crypt
        run: make LDFLAGS="-static-libstdc++ -static -lcrypto -lws2_32"

      - name: Create Release
        if: contains(github.ref, 'release')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: zip artifacts
        run: |
          zip --junk-paths -r git-crypt-windows.zip git-crypt.exe

      - name: Upload Release Asset
        if: contains(github.ref, 'release')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./git-crypt-windows.zip
          asset_name: git-crypt-windows.zip
          asset_content_type: application/zip
